# Generated by Django 2.0.2 on 2018-06-29 05:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Inquiry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, null=True, verbose_name='新增时间')),
                ('modified', models.DateTimeField(auto_now=True, null=True, verbose_name='修改时间')),
                ('customer', models.TextField(blank=True, default=None, null=True, verbose_name='客户')),
                ('created_by', models.ForeignKey(blank=True, default=None, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='example_app_inquiry_created', to=settings.AUTH_USER_MODEL, verbose_name='新建人')),
                ('modified_by', models.ForeignKey(blank=True, default=None, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='example_app_inquiry_modified', to=settings.AUTH_USER_MODEL, verbose_name='修改人')),
                ('sales', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='销售')),
            ],
            options={
                'verbose_name': '询单',
                'permissions': (('v_can_view_own', 'Can View Own 询单'), ('v_can_view_all', 'Can View All 询单'), ('v_can_submit_own', 'Can Submit Own 询单'), ('v_can_submit_all', 'Can Submit All 询单'), ('v_can_retract_own', 'Can Retract Own 询单'), ('v_can_retract_all', 'Can Retract All 询单'), ('p_can_handover_all', 'Can Handover All 询单'), ('p_can_approve_all', 'Can_Approve All_询单')),
            },
        ),
        migrations.CreateModel(
            name='InquiryInline',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, null=True, verbose_name='新增时间')),
                ('modified', models.DateTimeField(auto_now=True, null=True, verbose_name='修改时间')),
                ('cat_no', models.TextField(blank=True, default=None, null=True, verbose_name='货号')),
                ('cas', models.TextField(blank=True, default=None, null=True, verbose_name='cas')),
                ('name', models.TextField(blank=True, default=None, null=True, verbose_name='名称')),
                ('quantity_unit', models.FloatField(blank=True, default=None, null=True, verbose_name='单位数量')),
                ('unit', models.TextField(blank=True, choices=[('g', 'g'), ('kg', 'kg'), ('mg', 'mg'), ('ml', 'ml'), ('ul', 'ul'), ('L', 'L')], default='mg', null=True, verbose_name='单位')),
                ('quantity', models.PositiveIntegerField(blank=True, default=1, verbose_name='数量')),
                ('created_by', models.ForeignKey(blank=True, default=None, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='example_app_inquiryinline_created', to=settings.AUTH_USER_MODEL, verbose_name='新建人')),
                ('modified_by', models.ForeignKey(blank=True, default=None, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='example_app_inquiryinline_modified', to=settings.AUTH_USER_MODEL, verbose_name='修改人')),
                ('parent_voucher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inlines', to='example_app.Inquiry', verbose_name='单据')),
            ],
            options={
                'verbose_name': '询单内联',
            },
        ),
        migrations.CreateModel(
            name='MyVoucher',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, null=True, verbose_name='新增时间')),
                ('modified', models.DateTimeField(auto_now=True, null=True, verbose_name='修改时间')),
                ('to', models.TextField(blank=True, default=None, null=True)),
                ('want_to', models.TextField(blank=True, default=None, null=True)),
                ('before', models.DateField(blank=True, default=None, null=True)),
                ('created_by', models.ForeignKey(blank=True, default=None, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='example_app_myvoucher_created', to=settings.AUTH_USER_MODEL, verbose_name='新建人')),
                ('modified_by', models.ForeignKey(blank=True, default=None, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='example_app_myvoucher_modified', to=settings.AUTH_USER_MODEL, verbose_name='修改人')),
            ],
            options={
                'verbose_name': '测试单据',
                'permissions': (('v_can_view_own', 'Can View Own 测试单据'), ('v_can_view_all', 'Can View All 测试单据'), ('v_can_submit_own', 'Can Submit Own 测试单据'), ('v_can_submit_all', 'Can Submit All 测试单据'), ('v_can_retract_own', 'Can Retract Own 测试单据'), ('v_can_retract_all', 'Can Retract All 测试单据'), ('p_can_handover_all', 'Can Handover All 测试单据'), ('p_can_approve_all', 'Can_Approve All_测试单据')),
            },
        ),
        migrations.CreateModel(
            name='Quotation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, null=True, verbose_name='新增时间')),
                ('modified', models.DateTimeField(auto_now=True, null=True, verbose_name='修改时间')),
                ('product_cat_no', models.TextField()),
                ('source_id', models.PositiveIntegerField(blank=True, default=None, editable=False, null=True)),
                ('created_by', models.ForeignKey(blank=True, default=None, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='example_app_quotation_created', to=settings.AUTH_USER_MODEL, verbose_name='新建人')),
                ('modified_by', models.ForeignKey(blank=True, default=None, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='example_app_quotation_modified', to=settings.AUTH_USER_MODEL, verbose_name='修改人')),
                ('source_type', models.ForeignKey(blank=True, default=None, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType')),
            ],
            options={
                'verbose_name': '报价列表',
                'permissions': (('v_can_view_own', 'Can View Own 报价列表'), ('v_can_view_all', 'Can View All 报价列表'), ('v_can_submit_own', 'Can Submit Own 报价列表'), ('v_can_submit_all', 'Can Submit All 报价列表'), ('v_can_retract_own', 'Can Retract Own 报价列表'), ('v_can_retract_all', 'Can Retract All 报价列表'), ('p_can_handover_all', 'Can Handover All 报价列表'), ('p_can_approve_all', 'Can_Approve All_报价列表')),
            },
        ),
    ]
