# Generated by Django 2.0.2 on 2018-03-04 09:31

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Inquiry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, null=True, verbose_name='新增时间')),
                ('modified', models.DateTimeField(auto_now=True, null=True, verbose_name='修改时间')),
                ('cat_no', models.TextField(blank=True, default=None, null=True)),
                ('cas', models.TextField(blank=True, default=None, null=True)),
                ('name', models.TextField(blank=True, default=None, null=True)),
                ('quantity_unit', models.FloatField(blank=True, default=None, null=True)),
                ('unit', models.TextField(blank=True, default=None, null=True)),
                ('quantity', models.PositiveIntegerField(blank=True, default=1)),
                ('created_by', models.ForeignKey(blank=True, default=None, editable=False, null=True, on_delete='CASCADE', related_name='test_app_inquiry_created', to=settings.AUTH_USER_MODEL, verbose_name='新建人')),
                ('modified_by', models.ForeignKey(blank=True, default=None, editable=False, null=True, on_delete='CASCADE', related_name='test_app_inquiry_modified', to=settings.AUTH_USER_MODEL, verbose_name='修改人')),
            ],
            options={
                'permissions': (('v_can_view_own_inquiry', 'Can View Own Inquiry'), ('v_can_view_all_inquiry', 'Can View All Inquiry'), ('v_can_submit_own_inquiry', 'Can Submit Own Inquiry'), ('v_can_submit_all_inquiry', 'Can Submit All Inquiry'), ('v_can_retract_own_inquiry', 'Can Retract Own Inquiry'), ('v_can_retract_all_inquiry', 'Can Retract All Inquiry'), ('p_can_handover_all_inquiry', 'Can Handover All Inquiry'), ('p_can_approve_all_inquiry', 'Can_Approve All_Inquiry')),
            },
        ),
        migrations.CreateModel(
            name='MyVoucher',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, null=True, verbose_name='新增时间')),
                ('modified', models.DateTimeField(auto_now=True, null=True, verbose_name='修改时间')),
                ('to', models.TextField(blank=True, default=None, null=True)),
                ('want_to', models.TextField(blank=True, default=None, null=True)),
                ('before', models.DateField(blank=True, default=None, null=True)),
                ('created_by', models.ForeignKey(blank=True, default=None, editable=False, null=True, on_delete='CASCADE', related_name='test_app_myvoucher_created', to=settings.AUTH_USER_MODEL, verbose_name='新建人')),
                ('modified_by', models.ForeignKey(blank=True, default=None, editable=False, null=True, on_delete='CASCADE', related_name='test_app_myvoucher_modified', to=settings.AUTH_USER_MODEL, verbose_name='修改人')),
            ],
            options={
                'permissions': (('v_can_view_own_myvoucher', 'Can View Own MyVoucher'), ('v_can_view_all_myvoucher', 'Can View All MyVoucher'), ('v_can_submit_own_myvoucher', 'Can Submit Own MyVoucher'), ('v_can_submit_all_myvoucher', 'Can Submit All MyVoucher'), ('v_can_retract_own_myvoucher', 'Can Retract Own MyVoucher'), ('v_can_retract_all_myvoucher', 'Can Retract All MyVoucher'), ('p_can_handover_all_myvoucher', 'Can Handover All MyVoucher'), ('p_can_approve_all_myvoucher', 'Can_Approve All_MyVoucher')),
            },
        ),
    ]
