# Generated by Django 2.0.2 on 2018-06-29 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('example_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inquiryinline',
            name='unit',
            field=models.TextField(blank=True, choices=[('mg', 'mg'), ('g', 'g'), ('kg', 'kg'), ('L', 'L'), ('ul', 'ul'), ('ml', 'ml')], default='mg', null=True, verbose_name='单位'),
        ),
    ]
