# Generated by Django 2.0.2 on 2018-03-06 13:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('contenttypes', '0002_remove_content_type_name'),
        ('example_app', '0002_auto_20180306_1521'),
    ]

    operations = [
        migrations.CreateModel(
            name='Quotation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, null=True, verbose_name='新增时间')),
                ('modified', models.DateTimeField(auto_now=True, null=True, verbose_name='修改时间')),
                ('source_id', models.PositiveIntegerField(blank=True, default=None, null=True)),
                ('product_cat_no', models.TextField()),
                ('created_by', models.ForeignKey(blank=True, default=None, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='test_app_quotation_created', to=settings.AUTH_USER_MODEL, verbose_name='新建人')),
                ('modified_by', models.ForeignKey(blank=True, default=None, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='test_app_quotation_modified', to=settings.AUTH_USER_MODEL, verbose_name='修改人')),
                ('source_type', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType')),
            ],
            options={
                'permissions': (('v_can_view_own', 'Can View Own Quotation'), ('v_can_view_all', 'Can View All Quotation'), ('v_can_submit_own', 'Can Submit Own Quotation'), ('v_can_submit_all', 'Can Submit All Quotation'), ('v_can_retract_own', 'Can Retract Own Quotation'), ('v_can_retract_all', 'Can Retract All Quotation'), ('p_can_handover_all', 'Can Handover All Quotation'), ('p_can_approve_all', 'Can_Approve All_Quotation')),
            },
        ),
        migrations.AlterField(
            model_name='inquiryinline',
            name='unit',
            field=models.TextField(blank=True, choices=[('ul', 'ul'), ('mg', 'mg'), ('kg', 'kg'), ('g', 'g'), ('L', 'L'), ('ml', 'ml')], default='mg', null=True, verbose_name='单位'),
        ),
    ]
