# Generated by Django 2.0.2 on 2018-06-29 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('example_app', '0002_auto_20180629_1335'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inquiryinline',
            name='unit',
            field=models.TextField(blank=True, choices=[('g', 'g'), ('kg', 'kg'), ('ml', 'ml'), ('ul', 'ul'), ('mg', 'mg'), ('L', 'L')], default='mg', null=True, verbose_name='单位'),
        ),
    ]
