# Generated by Django 2.0.2 on 2018-03-06 13:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('example_app', '0003_auto_20180306_2141'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inquiry',
            name='created_by',
            field=models.ForeignKey(blank=True, default=None, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='example_app_inquiry_created', to=settings.AUTH_USER_MODEL, verbose_name='新建人'),
        ),
        migrations.AlterField(
            model_name='inquiry',
            name='modified_by',
            field=models.ForeignKey(blank=True, default=None, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='example_app_inquiry_modified', to=settings.AUTH_USER_MODEL, verbose_name='修改人'),
        ),
        migrations.AlterField(
            model_name='inquiryinline',
            name='created_by',
            field=models.ForeignKey(blank=True, default=None, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='example_app_inquiryinline_created', to=settings.AUTH_USER_MODEL, verbose_name='新建人'),
        ),
        migrations.AlterField(
            model_name='inquiryinline',
            name='modified_by',
            field=models.ForeignKey(blank=True, default=None, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='example_app_inquiryinline_modified', to=settings.AUTH_USER_MODEL, verbose_name='修改人'),
        ),
        migrations.AlterField(
            model_name='inquiryinline',
            name='unit',
            field=models.TextField(blank=True, choices=[('kg', 'kg'), ('mg', 'mg'), ('L', 'L'), ('g', 'g'), ('ml', 'ml'), ('ul', 'ul')], default='mg', null=True, verbose_name='单位'),
        ),
        migrations.AlterField(
            model_name='myvoucher',
            name='created_by',
            field=models.ForeignKey(blank=True, default=None, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='example_app_myvoucher_created', to=settings.AUTH_USER_MODEL, verbose_name='新建人'),
        ),
        migrations.AlterField(
            model_name='myvoucher',
            name='modified_by',
            field=models.ForeignKey(blank=True, default=None, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='example_app_myvoucher_modified', to=settings.AUTH_USER_MODEL, verbose_name='修改人'),
        ),
        migrations.AlterField(
            model_name='quotation',
            name='created_by',
            field=models.ForeignKey(blank=True, default=None, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='example_app_quotation_created', to=settings.AUTH_USER_MODEL, verbose_name='新建人'),
        ),
        migrations.AlterField(
            model_name='quotation',
            name='modified_by',
            field=models.ForeignKey(blank=True, default=None, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='example_app_quotation_modified', to=settings.AUTH_USER_MODEL, verbose_name='修改人'),
        ),
    ]
