# Generated by Django 2.0.2 on 2018-03-10 01:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('example_app', '0004_auto_20180306_2151'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='quotation',
            options={'permissions': (('v_can_view_own', 'Can View Own 报价列表'), ('v_can_view_all', 'Can View All 报价列表'), ('v_can_submit_own', 'Can Submit Own 报价列表'), ('v_can_submit_all', 'Can Submit All 报价列表'), ('v_can_retract_own', 'Can Retract Own 报价列表'), ('v_can_retract_all', 'Can Retract All 报价列表'), ('p_can_handover_all', 'Can Handover All 报价列表'), ('p_can_approve_all', 'Can_Approve All_报价列表')), 'verbose_name': '报价列表'},
        ),
        migrations.AlterField(
            model_name='inquiryinline',
            name='unit',
            field=models.TextField(blank=True, choices=[('g', 'g'), ('L', 'L'), ('mg', 'mg'), ('kg', 'kg'), ('ml', 'ml'), ('ul', 'ul')], default='mg', null=True, verbose_name='单位'),
        ),
    ]
