# Generated by Django 2.0.2 on 2018-03-10 01:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('example_app', '0005_auto_20180310_0909'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inquiryinline',
            name='unit',
            field=models.TextField(blank=True, choices=[('mg', 'mg'), ('kg', 'kg'), ('g', 'g'), ('ml', 'ml'), ('ul', 'ul'), ('L', 'L')], default='mg', null=True, verbose_name='单位'),
        ),
    ]
