# Generated by Django 2.0.2 on 2018-05-24 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('example_app', '0007_auto_20180310_1003'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inquiryinline',
            name='unit',
            field=models.TextField(blank=True, choices=[('ul', 'ul'), ('kg', 'kg'), ('g', 'g'), ('L', 'L'), ('ml', 'ml'), ('mg', 'mg')], default='mg', null=True, verbose_name='单位'),
        ),
    ]
