# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-06-28 15:19
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('example_app', '0007_auto_20180310_1003'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inquiryinline',
            name='unit',
            field=models.TextField(blank=True, choices=[('ul', 'ul'), ('mg', 'mg'), ('g', 'g'), ('ml', 'ml'), ('kg', 'kg'), ('L', 'L')], default='mg', null=True, verbose_name='单位'),
        ),
        migrations.AlterField(
            model_name='quotation',
            name='source_id',
            field=models.PositiveIntegerField(blank=True, default=None, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='quotation',
            name='source_type',
            field=models.ForeignKey(blank=True, default=None, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType'),
        ),
    ]
