# Generated by Django 2.0.2 on 2018-05-24 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('example_app', '0008_auto_20180524_1346'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inquiryinline',
            name='unit',
            field=models.TextField(blank=True, choices=[('mg', 'mg'), ('ul', 'ul'), ('g', 'g'), ('ml', 'ml'), ('L', 'L'), ('kg', 'kg')], default='mg', null=True, verbose_name='单位'),
        ),
    ]
