# Generated by Django 2.0.6 on 2018-06-28 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('example_app', '0008_auto_20180628_2319'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inquiryinline',
            name='unit',
            field=models.TextField(blank=True, choices=[('ul', 'ul'), ('L', 'L'), ('ml', 'ml'), ('kg', 'kg'), ('mg', 'mg'), ('g', 'g')], default='mg', null=True, verbose_name='单位'),
        ),
    ]
