# Generated by Django 2.0.6 on 2018-06-28 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('example_app', '0009_auto_20180628_2334'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inquiryinline',
            name='unit',
            field=models.TextField(blank=True, choices=[('kg', 'kg'), ('g', 'g'), ('L', 'L'), ('ul', 'ul'), ('mg', 'mg'), ('ml', 'ml')], default='mg', null=True, verbose_name='单位'),
        ),
    ]
