# Generated by Django 2.0.6 on 2018-06-28 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('example_app', '0010_auto_20180628_2358'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inquiryinline',
            name='unit',
            field=models.TextField(blank=True, choices=[('ul', 'ul'), ('ml', 'ml'), ('kg', 'kg'), ('L', 'L'), ('g', 'g'), ('mg', 'mg')], default='mg', null=True, verbose_name='单位'),
        ),
    ]
