# Generated by Django 2.0.2 on 2018-03-03 08:18

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MyVoucher',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, null=True, verbose_name='新增时间')),
                ('modified', models.DateTimeField(auto_now=True, null=True, verbose_name='修改时间')),
                ('to', models.TextField(blank=True, default=None, null=True)),
                ('want_to', models.TextField(blank=True, default=None, null=True)),
                ('before', models.DateField(blank=True, default=None, null=True)),
                ('created_by', models.ForeignKey(blank=True, default=None, editable=False, null=True, on_delete='CASCADE', related_name='test_app_myvoucher_created', to=settings.AUTH_USER_MODEL, verbose_name='新建人')),
                ('modified_by', models.ForeignKey(blank=True, default=None, editable=False, null=True, on_delete='CASCADE', related_name='test_app_myvoucher_modified', to=settings.AUTH_USER_MODEL, verbose_name='修改人')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
