# Generated by Django 2.0.6 on 2018-06-28 15:59

import annoying.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import json
import workflow.models.flow


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Flow',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, null=True, verbose_name='新增时间')),
                ('modified', models.DateTimeField(auto_now=True, null=True, verbose_name='修改时间')),
                ('name', models.TextField()),
                ('in_use', models.BooleanField(default=False)),
                ('created_by', models.ForeignKey(blank=True, default=None, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='workflow_flow_created', to=settings.AUTH_USER_MODEL, verbose_name='新建人')),
                ('modified_by', models.ForeignKey(blank=True, default=None, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='workflow_flow_modified', to=settings.AUTH_USER_MODEL, verbose_name='修改人')),
                ('voucher_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='contenttypes.ContentType')),
            ],
        ),
        migrations.CreateModel(
            name='Node',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, null=True, verbose_name='新增时间')),
                ('modified', models.DateTimeField(auto_now=True, null=True, verbose_name='修改时间')),
                ('node_type', models.CharField(choices=[('START', '开始'), ('END', '结束'), ('USER', '用户节点'), ('SYS', '系统节点')], max_length=100)),
                ('is_start', models.BooleanField(default=False)),
                ('name', models.TextField(null=True)),
                ('prompt', models.TextField(blank=True, null=True)),
                ('condition', workflow.models.flow.CustomJSONField(blank=True, default={'field': None, 'negative_node_id': None, 'operator': None, 'positive_node_id': None, 'type': None, 'value': None}, deserializer=json.loads, null=True, serializer=annoying.fields.dumps)),
                ('created_by', models.ForeignKey(blank=True, default=None, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='workflow_node_created', to=settings.AUTH_USER_MODEL, verbose_name='新建人')),
                ('flow', models.ForeignKey(db_column='flow_id', on_delete=django.db.models.deletion.PROTECT, to='workflow.Flow')),
                ('modified_by', models.ForeignKey(blank=True, default=None, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='workflow_node_modified', to=settings.AUTH_USER_MODEL, verbose_name='修改人')),
            ],
            options={
                'ordering': ['flow', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Proceeding',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, null=True, verbose_name='新增时间')),
                ('modified', models.DateTimeField(auto_now=True, null=True, verbose_name='修改时间')),
                ('status', models.CharField(choices=[('PROCESSING', '进行中'), ('POS_CLOSED', '关闭'), ('REJECTED', '驳回'), ('APPROVED', '通过'), ('RETRACTED', '撤回')], default='PROCESSING', max_length=100, verbose_name='状态')),
                ('voucher_obj_id', models.PositiveIntegerField()),
                ('created_by', models.ForeignKey(blank=True, default=None, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='workflow_proceeding_created', to=settings.AUTH_USER_MODEL, verbose_name='新建人')),
                ('flow', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='workflow.Flow')),
                ('modified_by', models.ForeignKey(blank=True, default=None, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='workflow_proceeding_modified', to=settings.AUTH_USER_MODEL, verbose_name='修改人')),
                ('node', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='workflow.Node')),
                ('voucher_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='contenttypes.ContentType')),
            ],
        ),
        migrations.CreateModel(
            name='ProcessLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, null=True, verbose_name='新增时间')),
                ('modified', models.DateTimeField(auto_now=True, null=True, verbose_name='修改时间')),
                ('created_by', models.ForeignKey(blank=True, default=None, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='workflow_processlog_created', to=settings.AUTH_USER_MODEL, verbose_name='新建人')),
                ('modified_by', models.ForeignKey(blank=True, default=None, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='workflow_processlog_modified', to=settings.AUTH_USER_MODEL, verbose_name='修改人')),
                ('proceeding', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='workflow.Proceeding')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, null=True, verbose_name='新增时间')),
                ('modified', models.DateTimeField(auto_now=True, null=True, verbose_name='修改时间')),
                ('name', models.TextField(null=True)),
                ('prompt', models.TextField(blank=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, default=None, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='workflow_transaction_created', to=settings.AUTH_USER_MODEL, verbose_name='新建人')),
                ('flow', models.ForeignKey(db_column='flow_id', on_delete=django.db.models.deletion.PROTECT, to='workflow.Flow')),
                ('modified_by', models.ForeignKey(blank=True, default=None, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='workflow_transaction_modified', to=settings.AUTH_USER_MODEL, verbose_name='修改人')),
                ('next_node', models.ForeignKey(blank=True, default=None, limit_choices_to=models.Q(flow=models.ForeignKey(db_column='flow_id', on_delete=django.db.models.deletion.PROTECT, to='workflow.Flow')), null=True, on_delete=django.db.models.deletion.PROTECT, related_name='previous_transaction', to='workflow.Node')),
                ('previous_node', models.ForeignKey(blank=True, default=None, limit_choices_to=models.Q(flow=models.ForeignKey(db_column='flow_id', on_delete=django.db.models.deletion.PROTECT, to='workflow.Flow')), null=True, on_delete=django.db.models.deletion.PROTECT, related_name='next_transaction', to='workflow.Node')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AlterUniqueTogether(
            name='node',
            unique_together={('flow', 'name')},
        ),
        migrations.AlterUniqueTogether(
            name='flow',
            unique_together={('voucher_type', 'in_use')},
        ),
    ]
