# Generated by Django 2.0.2 on 2018-03-04 09:31

import annoying.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.query_utils
import json


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Flow',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, null=True, verbose_name='新增时间')),
                ('modified', models.DateTimeField(auto_now=True, null=True, verbose_name='修改时间')),
                ('name', models.TextField()),
                ('in_use', models.BooleanField(default=False)),
                ('copy_to', models.ManyToManyField(to=settings.AUTH_USER_MODEL, verbose_name='抄送')),
                ('created_by', models.ForeignKey(blank=True, default=None, editable=False, null=True, on_delete='CASCADE', related_name='workflow_flow_created', to=settings.AUTH_USER_MODEL, verbose_name='新建人')),
                ('modified_by', models.ForeignKey(blank=True, default=None, editable=False, null=True, on_delete='CASCADE', related_name='workflow_flow_modified', to=settings.AUTH_USER_MODEL, verbose_name='修改人')),
                ('process_obj', models.ForeignKey(on_delete='CASCADE', to='contenttypes.ContentType')),
            ],
        ),
        migrations.CreateModel(
            name='FlowNode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, null=True, verbose_name='新增时间')),
                ('modified', models.DateTimeField(auto_now=True, null=True, verbose_name='修改时间')),
                ('name', models.TextField(null=True)),
                ('prompt', models.TextField(blank=True, null=True)),
                ('node_type', models.CharField(choices=[('START', '开始'), ('END', '结束'), ('USER', '用户节点'), ('SYS', '系统节点')], max_length=100)),
                ('approval_group_id', models.PositiveIntegerField(null=True)),
                ('forward_condition', annoying.fields.JSONField(blank=True, default={'attr': None, 'operator': None, 'type': None, 'value': None}, deserializer=json.loads, null=True, serializer=annoying.fields.dumps)),
                ('approval_group_type', models.ForeignKey(limit_choices_to=django.db.models.query_utils.Q(('app_label', 'auth'), django.db.models.query_utils.Q(('model', 'user'), ('model', 'group'), _connector='OR'), _connector='AND'), null=True, on_delete='CASCADE', to='contenttypes.ContentType')),
                ('backward_node', models.ForeignKey(null=True, on_delete='CASCADE', related_name='forward', to='workflow.FlowNode')),
                ('created_by', models.ForeignKey(blank=True, default=None, editable=False, null=True, on_delete='CASCADE', related_name='workflow_flownode_created', to=settings.AUTH_USER_MODEL, verbose_name='新建人')),
                ('flow', models.ForeignKey(db_column='flow_id', on_delete='CASCADE', to='workflow.Flow')),
                ('forward_node', models.ForeignKey(null=True, on_delete='CASCADE', related_name='backword', to='workflow.FlowNode')),
                ('modified_by', models.ForeignKey(blank=True, default=None, editable=False, null=True, on_delete='CASCADE', related_name='workflow_flownode_modified', to=settings.AUTH_USER_MODEL, verbose_name='修改人')),
            ],
        ),
        migrations.CreateModel(
            name='Proceeding',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, null=True, verbose_name='新增时间')),
                ('modified', models.DateTimeField(auto_now=True, null=True, verbose_name='修改时间')),
                ('status', models.CharField(choices=[('PROCESSING', '进行中'), ('POS_CLOSED', '关闭'), ('REJECTED', '驳回'), ('APPROVED', '通过'), ('RETRACTED', '撤回')], default='PROCESSING', max_length=100, verbose_name='状态')),
                ('voucher_obj_id', models.PositiveIntegerField()),
                ('created_by', models.ForeignKey(blank=True, default=None, editable=False, null=True, on_delete='CASCADE', related_name='workflow_proceeding_created', to=settings.AUTH_USER_MODEL, verbose_name='新建人')),
                ('flow', models.ForeignKey(on_delete='CASCADE', to='workflow.Flow')),
                ('modified_by', models.ForeignKey(blank=True, default=None, editable=False, null=True, on_delete='CASCADE', related_name='workflow_proceeding_modified', to=settings.AUTH_USER_MODEL, verbose_name='修改人')),
                ('voucher_type', models.ForeignKey(on_delete='CASCADE', to='contenttypes.ContentType')),
                ('workflow_node', models.ForeignKey(on_delete='CASCADE', to='workflow.FlowNode')),
            ],
        ),
        migrations.CreateModel(
            name='ProcessLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, null=True, verbose_name='新增时间')),
                ('modified', models.DateTimeField(auto_now=True, null=True, verbose_name='修改时间')),
                ('created_by', models.ForeignKey(blank=True, default=None, editable=False, null=True, on_delete='CASCADE', related_name='workflow_processlog_created', to=settings.AUTH_USER_MODEL, verbose_name='新建人')),
                ('modified_by', models.ForeignKey(blank=True, default=None, editable=False, null=True, on_delete='CASCADE', related_name='workflow_processlog_modified', to=settings.AUTH_USER_MODEL, verbose_name='修改人')),
                ('proceeding', models.ForeignKey(on_delete='CASCADE', to='workflow.Proceeding')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AlterUniqueTogether(
            name='flownode',
            unique_together={('flow', 'name')},
        ),
        migrations.AlterUniqueTogether(
            name='flow',
            unique_together={('process_obj', 'in_use')},
        ),
    ]
