# Generated by Django 2.0.2 on 2018-06-29 05:35

import annoying.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import json
import workflow.models.flow


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Flow',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, null=True, verbose_name='新增时间')),
                ('modified', models.DateTimeField(auto_now=True, null=True, verbose_name='修改时间')),
                ('name', models.TextField()),
                ('created_by', models.ForeignKey(blank=True, default=None, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='workflow_flow_created', to=settings.AUTH_USER_MODEL, verbose_name='新建人')),
                ('modified_by', models.ForeignKey(blank=True, default=None, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='workflow_flow_modified', to=settings.AUTH_USER_MODEL, verbose_name='修改人')),
            ],
        ),
        migrations.CreateModel(
            name='FlowVoucher',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('flow', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='workflow.Flow')),
                ('voucher_type', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='contenttypes.ContentType')),
            ],
        ),
        migrations.CreateModel(
            name='Node',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, null=True, verbose_name='新增时间')),
                ('modified', models.DateTimeField(auto_now=True, null=True, verbose_name='修改时间')),
                ('name', models.TextField(null=True)),
                ('prompt', models.TextField(blank=True, null=True)),
                ('editable', models.BooleanField(default=True)),
                ('is_start', models.BooleanField(default=False)),
                ('is_end', models.BooleanField(default=False)),
                ('created_by', models.ForeignKey(blank=True, default=None, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='workflow_node_created', to=settings.AUTH_USER_MODEL, verbose_name='新建人')),
                ('flow', models.ForeignKey(db_column='flow_id', on_delete=django.db.models.deletion.PROTECT, to='workflow.Flow')),
                ('modified_by', models.ForeignKey(blank=True, default=None, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='workflow_node_modified', to=settings.AUTH_USER_MODEL, verbose_name='修改人')),
            ],
            options={
                'ordering': ['flow', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Proceeding',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, null=True, verbose_name='新增时间')),
                ('modified', models.DateTimeField(auto_now=True, null=True, verbose_name='修改时间')),
                ('voucher_obj_id', models.PositiveIntegerField()),
                ('created_by', models.ForeignKey(blank=True, default=None, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='workflow_proceeding_created', to=settings.AUTH_USER_MODEL, verbose_name='新建人')),
                ('flow', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='workflow.Flow')),
                ('modified_by', models.ForeignKey(blank=True, default=None, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='workflow_proceeding_modified', to=settings.AUTH_USER_MODEL, verbose_name='修改人')),
                ('node', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='workflow.Node')),
                ('voucher_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='contenttypes.ContentType')),
            ],
        ),
        migrations.CreateModel(
            name='ProcessLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, null=True, verbose_name='新增时间')),
                ('modified', models.DateTimeField(auto_now=True, null=True, verbose_name='修改时间')),
                ('created_by', models.ForeignKey(blank=True, default=None, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='workflow_processlog_created', to=settings.AUTH_USER_MODEL, verbose_name='新建人')),
                ('modified_by', models.ForeignKey(blank=True, default=None, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='workflow_processlog_modified', to=settings.AUTH_USER_MODEL, verbose_name='修改人')),
                ('proceeding', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='workflow.Proceeding')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, null=True, verbose_name='新增时间')),
                ('modified', models.DateTimeField(auto_now=True, null=True, verbose_name='修改时间')),
                ('name', models.TextField(null=True)),
                ('prompt', models.TextField(blank=True, null=True)),
                ('transaction_type', models.CharField(choices=[('USER', 'User Transaction'), ('SYS', 'System Transaction')], default='USER', max_length=100)),
                ('condition', workflow.models.flow.CustomJSONField(blank=True, default={'field': None, 'negative_node_id': None, 'operator': None, 'positive_node_id': None, 'type': None, 'value': None}, deserializer=json.loads, null=True, serializer=annoying.fields.dumps)),
                ('created_by', models.ForeignKey(blank=True, default=None, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='workflow_transaction_created', to=settings.AUTH_USER_MODEL, verbose_name='新建人')),
                ('flow', models.ForeignKey(db_column='flow_id', on_delete=django.db.models.deletion.PROTECT, to='workflow.Flow')),
                ('modified_by', models.ForeignKey(blank=True, default=None, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='workflow_transaction_modified', to=settings.AUTH_USER_MODEL, verbose_name='修改人')),
                ('next_node', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='previous_transactions', to='workflow.Node')),
                ('previous_node', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='next_transactions', to='workflow.Node')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AlterUniqueTogether(
            name='proceeding',
            unique_together={('voucher_type', 'voucher_obj_id')},
        ),
        migrations.AlterUniqueTogether(
            name='node',
            unique_together={('flow', 'name'), ('flow', 'is_start')},
        ),
    ]
