# Generated by Django 2.0.2 on 2018-03-03 09:00

from django.db import migrations, models
import django.db.models.query_utils


class Migration(migrations.Migration):

    dependencies = [
        ('workflow', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flownode',
            name='approval_group_id',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='flownode',
            name='approval_group_type',
            field=models.ForeignKey(limit_choices_to=django.db.models.query_utils.Q(('app_label', 'auth'), django.db.models.query_utils.Q(('model', 'user'), ('model', 'group'), _connector='OR'), _connector='AND'), null=True, on_delete='CASCADE', to='contenttypes.ContentType'),
        ),
    ]
