# Generated by Django 2.0.2 on 2018-03-06 07:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.db.models.query_utils


class Migration(migrations.Migration):

    dependencies = [
        ('workflow', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='flownode',
            old_name='forward_condition',
            new_name='condition',
        ),
        migrations.RemoveField(
            model_name='flownode',
            name='backward_node',
        ),
        migrations.RemoveField(
            model_name='flownode',
            name='forward_node',
        ),
        migrations.RemoveField(
            model_name='proceeding',
            name='workflow_node',
        ),
        migrations.AddField(
            model_name='flownode',
            name='next_node',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='backword', to='workflow.FlowNode'),
        ),
        migrations.AddField(
            model_name='flownode',
            name='previous_node',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='forward', to='workflow.FlowNode'),
        ),
        migrations.AddField(
            model_name='proceeding',
            name='node',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='workflow.FlowNode'),
        ),
        migrations.AlterField(
            model_name='flow',
            name='created_by',
            field=models.ForeignKey(blank=True, default=None, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='workflow_flow_created', to=settings.AUTH_USER_MODEL, verbose_name='新建人'),
        ),
        migrations.AlterField(
            model_name='flow',
            name='modified_by',
            field=models.ForeignKey(blank=True, default=None, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='workflow_flow_modified', to=settings.AUTH_USER_MODEL, verbose_name='修改人'),
        ),
        migrations.AlterField(
            model_name='flow',
            name='process_obj',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType'),
        ),
        migrations.AlterField(
            model_name='flownode',
            name='approval_group_id',
            field=models.PositiveIntegerField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='flownode',
            name='approval_group_type',
            field=models.ForeignKey(blank=True, default=None, limit_choices_to=django.db.models.query_utils.Q(('app_label', 'auth'), django.db.models.query_utils.Q(('model', 'user'), ('model', 'group'), _connector='OR'), _connector='AND'), null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType'),
        ),
        migrations.AlterField(
            model_name='flownode',
            name='created_by',
            field=models.ForeignKey(blank=True, default=None, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='workflow_flownode_created', to=settings.AUTH_USER_MODEL, verbose_name='新建人'),
        ),
        migrations.AlterField(
            model_name='flownode',
            name='flow',
            field=models.ForeignKey(db_column='flow_id', on_delete=django.db.models.deletion.CASCADE, to='workflow.Flow'),
        ),
        migrations.AlterField(
            model_name='flownode',
            name='modified_by',
            field=models.ForeignKey(blank=True, default=None, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='workflow_flownode_modified', to=settings.AUTH_USER_MODEL, verbose_name='修改人'),
        ),
        migrations.AlterField(
            model_name='proceeding',
            name='created_by',
            field=models.ForeignKey(blank=True, default=None, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='workflow_proceeding_created', to=settings.AUTH_USER_MODEL, verbose_name='新建人'),
        ),
        migrations.AlterField(
            model_name='proceeding',
            name='flow',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='workflow.Flow'),
        ),
        migrations.AlterField(
            model_name='proceeding',
            name='modified_by',
            field=models.ForeignKey(blank=True, default=None, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='workflow_proceeding_modified', to=settings.AUTH_USER_MODEL, verbose_name='修改人'),
        ),
        migrations.AlterField(
            model_name='proceeding',
            name='voucher_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType'),
        ),
        migrations.AlterField(
            model_name='processlog',
            name='created_by',
            field=models.ForeignKey(blank=True, default=None, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='workflow_processlog_created', to=settings.AUTH_USER_MODEL, verbose_name='新建人'),
        ),
        migrations.AlterField(
            model_name='processlog',
            name='modified_by',
            field=models.ForeignKey(blank=True, default=None, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='workflow_processlog_modified', to=settings.AUTH_USER_MODEL, verbose_name='修改人'),
        ),
        migrations.AlterField(
            model_name='processlog',
            name='proceeding',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='workflow.Proceeding'),
        ),
    ]
