# Generated by Django 2.0.2 on 2018-03-10 01:25

import annoying.fields
from django.db import migrations
import json


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('workflow', '0003_auto_20180310_0909'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='flownode',
            options={'ordering': ['flow', 'name']},
        ),
        migrations.RenameField(
            model_name='flow',
            old_name='process_obj',
            new_name='voucher_type',
        ),
        migrations.AlterField(
            model_name='flownode',
            name='condition',
            field=annoying.fields.JSONField(blank=True, default={'field': None, 'negative_node_id': None, 'operator': None, 'positive_node_id': None, 'type': None, 'value': None}, deserializer=json.loads, null=True, serializer=annoying.fields.dumps),
        ),
        migrations.AlterUniqueTogether(
            name='flow',
            unique_together={('voucher_type', 'in_use')},
        ),
    ]
