# Generated by Django 2.0.2 on 2018-03-03 09:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workflow', '0003_auto_20180303_1702'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='proceeding',
            name='current_user',
        ),
    ]
