# Generated by Django 2.0.2 on 2018-03-03 09:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workflow', '0004_remove_proceeding_current_user'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='proceeding',
            unique_together=set(),
        ),
    ]
