# Generated by Django 2.0.2 on 2018-03-10 02:03

import annoying.fields
from django.db import migrations
import json
import workflow.models.flow


class Migration(migrations.Migration):

    dependencies = [
        ('workflow', '0004_auto_20180310_0925'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flownode',
            name='condition',
            field=workflow.models.flow.CustomJSONField(blank=True, default={'field': None, 'negative_node_id': None, 'operator': None, 'positive_node_id': None, 'type': None, 'value': None}, deserializer=json.loads, null=True, serializer=annoying.fields.dumps),
        ),
    ]
